;(function(){var Locate={oConfig:{sDevice:'phone',bDisableIp:false,bCookie:false,nCookieTime:1296*1e6,sCookieName:'pcLocate',sCookieType:'self',bGetRegion:false,bDebug:false,bDebugShow:false,sDebugType:'console',bRuning:false,sDataType:'',aStepTime:[],oCoor:{},oErr:{num:0,type:[]}},aCallbackQueue:[],fExtend:function(oOrigin,oNew,bOverride){for(var p in oNew){if(oNew.hasOwnProperty(p)&&(!oOrigin.hasOwnProperty(p)||bOverride))oOrigin[p]=oNew[p];}
return oOrigin;},fParseQuery:function(oObj){var sRet='';for(var i in oObj){if(oObj.hasOwnProperty(i)){sRet+='&'+i+'='+oObj[i];}}
return sRet;},fParseResult:function(sRet){if(!sRet)return;if(window.JSON&&typeof window.JSON.parse==='function'){return JSON.parse(sRet);}else{return eval('('+sRet+')');}},fStringifyResult:(function(){var fStringfiy=function(oInput){var bArray=function(arr){if(typeof Array.isArray==='function'){return Array.isArray(arr);}else{return Object.prototype.toString.call(arr)==='[object Array]';}}
var bObject=function(obj){return Object.prototype.toString.call(obj)==='[object Object]';}
var fParse=function(oInput){if(bArray(oInput)){for(var i=0;i<oInput.length;i++){oInput[i]=fParse(oInput[i]);}
return'['+oInput.join(',')+']';}else if(bObject(oInput)){var ret=[];for(var i in oInput){if(oInput.hasOwnProperty(i)){ret.push('"'+i+'":'+fParse(oInput[i]));}}
return'{'+ret.join(',')+'}';}else if(typeof oInput==="string"){return'"'+oInput.toString()+'"';}else{return oInput.toString();}}
return fParse(oInput);}
return function(oRet){if(window.JSON&&typeof window.JSON.stringify==='function'){return JSON.stringify(oRet);}else{return fStringfiy(oRet);}}})(),fSetCookie:function(name,value,time,type){var path="";if(type=="root"){path=" path=/; domain="+window.location.hostname.replace(/.+((\.\w+)\.com(\.cn)?)/,"$1")+";";}
document.cookie=name+"="+encodeURIComponent(value)+";"+path+" expires="+new Date(+new Date()+time).toGMTString();},fGetCookie:function(name){return decodeURIComponent(document.cookie.replace(new RegExp(".*(?:^|; )"+name+"=([^;]*).*|.*"),"$1"));},oGetScriptCb:{},fGetScript:function(oOption){var script=document.createElement("script"),callbackVal=oOption.callbackSuccName?oOption.callbackSuccName:'callback'+1*new Date,callbackName="Locate.oGetScriptCb."+callbackVal,add=/\?/.test(oOption.url)?"&":"?";Locate.oGetScriptCb[callbackVal]=function(json){script.jsonp=1;oOption.callbackSucc(json);};script.type="text/javascript";script.src=oOption.url+add+'callback='+callbackName;script.charset=oOption.charset||"UTF-8";script.onload=script.onreadystatechange=function(){if(!this.readyState||this.readyState=="loaded"||this.readyState=="complete"){Locate.fRemoveScript(this,oOption.callbackErr,oOption.interface,callbackVal);}};script.onerror=function(){Locate.fRemoveScript(this,oOption.callbackErr,oOption.interface,callbackVal);};document.getElementsByTagName("head")[0].appendChild(script);},fRemoveScript:function(script,callbackErr,interface,callbackVal){if(typeof script.jsonp==="undefined"){callbackErr(interface);}
if(script.clearAttributes){script.clearAttributes();}else{script.onload=script.onreadystatechange=script.onerror=null;}
script.parentNode.removeChild(script);delete Locate.oGetScriptCb[callbackVal];},fAddStepTime:function(sName){var aTime=Locate.oConfig.aStepTime,nFinished=+new Date,nUsed,nTotal;if(aTime.length){nUsed=nFinished-aTime[aTime.length-1].finished;nTotal=nFinished-aTime[0].finished;}else{nUsed=nTotal=0;}
aTime.push({step:sName,used:(nUsed/1000)+'s',nTotal:(nTotal/1000)+'s',finished:nFinished});},fGetPara:function(sName){var reg=new RegExp("(&|\\?)"+sName+"=([^&]*)(&|$)","i"),r=window.location.search.match(reg);if(r!=null)return unescape(r[2]);return'';},cbGetAddrByCoor:function(oData){if(!oData.error&&oData.cityCode){Locate.oConfig.bDebug&&Locate.fAddStepTime("request ipAreaCoordJson succeed, and data is correct");Locate.oConfig.sDataType='ipAreaCoordJson';if(!Locate.oConfig.bGetRegion){Locate.cbSucc(oData);}else{Locate.getRegion({cityCode:oData.cityCode});}}else{Locate.oConfig.bDebug&&Locate.fAddStepTime("request ipAreaCoordJson succeed, but data error");var err=Locate.oConfig.oErr
err.num+=1;err.type.push("ipAreaCoordJson");if(oData.error){err['ipAreaCoordJson']=oData.error;}else{err['ipAreaCoordJson']="返回的接口数据不正确";}
Locate.cbErr();}},cbGetAddrByIp:function(oData){if(!oData.err&&oData.cityCode){Locate.oConfig.bDebug&&Locate.fAddStepTime("request ipJson succeed, and data is correct");Locate.oConfig.sDataType='ipJson';if(!Locate.oConfig.bGetRegion){Locate.cbSucc(oData);}else{Locate.getRegion({cityCode:oData.cityCode});}}else{Locate.oConfig.bDebug&&Locate.fAddStepTime("request ipJson succeed, but data error");var err=Locate.oConfig.oErr
err.num+=1;err.type.push("ipJson");err['ipJson']=oData.err;if(oData.city){Locate.cbSucc(oData);}else{Locate.cbErr();}}},cbGetRegion:function(oData){if(oData.result&&oData.cityData&&oData.cityData.cityId){Locate.oConfig.bDebug&&Locate.fAddStepTime("request region_ipArea succeed, and data is correct");var oRetData=oData.cityData;Locate.oConfig.sDataType+='+region_ipArea';oRetData.pro+="省";oRetData.city=oRetData.cityUser=oRetData.name+"市";oRetData.cityCodeUser=oRetData.cityCode;oRetData.proCodeUser=oRetData.proCode;urlWap=oRetData.url.replace(/www\.pcauto\.com\.cn/,"m\.pcauto\.com\.cn/x");Locate.cbSucc(oRetData);}else{Locate.oConfig.bDebug&&Locate.fAddStepTime("request region_ipArea succeed, but data error");var err=Locate.oConfig.oErr
err.num+=1;err.type.push("region_ipArea");if(!oData.result&&oData.msg){err['region_ipArea']=oData.msg;}else{err['region_ipArea']="返回的接口数据不正确";}
Locate.cbErr();}},cbGetScriptErr:function(interface){Locate.oConfig.bDebug&&Locate.fAddStepTime(interface+"request failed");var oErr=Locate.oConfig.oErr;oErr.num+=1;oErr.type.push('interface');oErr['interface']=interface;Locate.cbErr();},cbSucc:function(oData){oData.oCoor=Locate.oConfig.oCoor;var oResult={dataType:Locate.oConfig.sDataType,expires:+new Date};oResult.data=oData;if(!Locate.oConfig.oErr.num){Locate.oConfig.oDataReturn=oResult;if(Locate.oConfig.bCookie){Locate.fSetCookie(Locate.oConfig.sCookieName,Locate.fStringifyResult(oResult),1024*24*3600*1000,Locate.oConfig.sCookieType);}}
Locate.cbEnd(oResult);},cbErr:function(){var oResult={};oResult.dataType=Locate.oConfig.sDataType='default';if(Locate.oConfig.oDataDefault){oResult.data=Locate.oConfig.oDataDefault;}
Locate.cbEnd(oResult);},cbEnd:function(oData){var aQueue=Locate.aCallbackQueue,i=0,length=aQueue.length;oData.err=Locate.oConfig.oErr;if(Locate.oConfig.bDebug){Locate.fAddStepTime("end");oData.debug=Locate.oConfig.aStepTime;Locate.oConfig.aStepTime=[];if(Locate.oConfig.bDebugShow){if(Locate.oConfig.sDebugType=='console'){console.log(oData.debug);}else if(Locate.oConfig.sDebugType=='alert'){alert(Locate.fStringifyResult(oData.debug));}}}
for(;i<length;i++){aQueue[i].call(Locate,oData);}
Locate.aCallbackQueue=[];Locate.oConfig.running=false;},getAddrByH5:function(){var _sel=this;_sel.oConfig.bDebug&&_sel.fAddStepTime("get coords by h5 start");navigator.geolocation.getCurrentPosition(getAddrBgCoords,getCoordsByH5Error,{timeout:1e4});_sel.h5ErrorTimer=setTimeout(function(){getCoordsByH5Error({code:3});},1e4)
function getCoordsByH5Error(error){clearTimeout(_sel.h5ErrorTimer);var oErr=Locate.oConfig.oErr;oErr.num+=1;oErr.type.push('h5');switch(error.code){case 1:oErr['h5']='RejectShare';break;case 2:oErr['h5']='GetError';break;case 3:oErr['h5']='Timeout';break;default:oErr['h5']='unknownErr'}
_sel.oConfig.bDebug&&_sel.fAddStepTime("get coords error: "+oErr['h5']);if(_sel.oConfig.bDisableIp){Locate.cbErr();}else{Locate.getAddrByIp({'sts':oErr['h5']});}}
function getAddrBgCoords(position){clearTimeout(_sel.h5ErrorTimer);_sel.oConfig.bDebug&&_sel.fAddStepTime("get coords succeed:lat:"+position.coords.latitude+", lng:"+position.coords.longitude+", start request ipAreaCoordJson to get addr");_sel.oConfig.oCoor.lat=position.coords.latitude;_sel.oConfig.oCoor.lng=position.coords.longitude;var lat=position.coords.latitude,lng=position.coords.longitude,url=location.protocol+"//whois.pconline.com.cn/ipAreaCoordJson.jsp?coords="+lng+","+lat+"&level=2";Locate.fGetScript({url:url,interface:'ipAreaCoordJson',callbackSucc:Locate.cbGetAddrByCoor,callbackSuccName:'cbGetAddrByCoor',callbackErr:Locate.cbGetScriptErr});}},getAddrByIp:function(oArgs){Locate.oConfig.bDebug&&Locate.fAddStepTime("start request ipJson to get addr");var url=location.protocol+'//whois.pconline.com.cn/ipJson.jsp?defaultCity=true';if(oArgs){url+=Locate.fParseQuery(oArgs);}
Locate.fGetScript({url:url,interface:'ipJson',callbackSucc:Locate.cbGetAddrByIp,callbackSuccName:'cbGetAddrByIp',callbackErr:Locate.cbGetScriptErr,charset:'GBK'});},getRegion:function(oArgs){Locate.oConfig.bDebug&&Locate.fAddStepTime("start request region_ipArea to get region");var url=location.protocol+'//price.pcauto.com.cn/interface/cms/region_ipArea.jsp?m=getCityById&encode=utf8';if(oArgs){url+=Locate.fParseQuery(oArgs);}
Locate.fGetScript({url:url,interface:'region_ipArea',callbackSucc:Locate.cbGetRegion,callbackSuccName:'cbGetRegion',callbackErr:Locate.cbGetScriptErr});},init:function(oArgs,callback){Locate.fExtend(Locate.oConfig,oArgs,true);callback&&Locate.run(callback);},run:function(callback){var oConfig=Locate.oConfig,oCookieData,now;if(oConfig.bDebug){Locate.fAddStepTime("start");if(!oConfig.bDebugShow&&Locate.fGetPara('locatedebug')=='true'){oConfig.bDebugShow=true;}}
Locate.aCallbackQueue.push(callback);if(!oConfig.running){oCookieData=Locate.fParseResult(Locate.fGetCookie(oConfig.sCookieName));now=+new Date;if(oConfig.bCookie&&oCookieData&&oCookieData.data&&(oCookieData.expires+Locate.oConfig.nCookieTime)>now){oCookieData.dataType+='+cookie';Locate.oConfig.bDebug&&Locate.fAddStepTime("return cookie");Locate.cbEnd(oCookieData);}else{oConfig.running=true;oConfig.oErr={num:0,type:[]};if(oConfig.sDevice=='phone'){Locate.getAddrByH5();}else{Locate.getAddrByIp({'sts':'devicePC'});}}}}};window.Locate=Locate;})();